const SearchData = [
  {
    id: 1,
    name: "Essential Hoodie",
    slug: "essential-hoodie",
    description: "Minimal oversized organic cotton hoodie for everyday comfort.",
    category: "hoodies",
    tags: ["oversized", "hoodie", "cotton", "black", "minimalist"],
  },
  {
    id: 2,
    name: "Ocean Hoodie",
    slug: "ocean-hoodie",
    description: "Comfortable heavyweight loopback fleece hoodie in a deep ocean blue wash.",
    category: "hoodies",
    tags: ["blue", "hoodie", "heavyweight", "fleece"],
  },
  {
    id: 3,
    name: "Sand Hoodie",
    slug: "sand-hoodie",
    description: "Warm desert sand colored pullover hoodie made from ultra-soft french terry.",
    category: "hoodies",
    tags: ["sand", "beige", "hoodie", "pullover", "soft"],
  },
  {
    id: 4,
    name: "Forest Oversize T-Shirt",
    slug: "forest-oversize-t-shirt",
    description: "Oversized silhouette cut from heavy 240gsm long-staple cotton in a dark forest green.",
    category: "t-shirts",
    tags: ["green", "oversized", "tee", "tshirt", "t-shirt", "cotton"],
  },
  {
    id: 5,
    name: "Classic Linen Shirt",
    slug: "classic-linen-shirt",
    description: "Breathable pure flax linen relaxed-fit button-down perfect for warm weather.",
    category: "shirts",
    tags: ["white", "linen", "button-down", "summer", "breathable"],
  },
  {
    id: 6,
    name: "Raw Edge Denim Jacket",
    slug: "raw-edge-denim-jacket",
    description: "Structured raw indigo denim jacket featuring drop shoulders and subtle raw edge detailing.",
    category: "outerwear",
    tags: ["indigo", "denim", "jacket", "outerwear", "streetwear"],
  },
  {
    id: 7,
    name: "Minimal Merino Crewneck",
    slug: "minimal-merino-crewneck",
    description: "Superfine merino wool knitted sweater offering lightweight yet thermal insulation.",
    category: "knitwear",
    tags: ["grey", "sweater", "merino", "wool", "crewneck"],
  },
  {
    id: 8,
    name: "Wide Leg Wool Trouser",
    slug: "wide-leg-wool-trouser",
    description: "Tailored flowing trousers made from premium virgin wool with twin pleats and fluid drape.",
    category: "pants",
    tags: ["black", "tailored", "wool", "trousers", "wide-leg"],
  },
  {
    id: 9,
    name: "Brushed Cotton Overshirt",
    slug: "brushed-cotton-overshirt",
    description: "Soft flannel-feel utility overshirt with dual chest pockets and horn buttons.",
    category: "shirts",
    tags: ["brown", "flannel", "overshirt", "utility", "brushed"],
  },
];

export default SearchData;
